--[[
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 09/08/23 09:41
---

-- SteamLibrary/steamapps/common/ProjectZomboid/projectzomboid/media/lua/server/Traps/TrapDefinition.lua

--local trap = require("server/Trap")
--local bait = require("server/Bait")
--local zone = require("server/Zone")

local trap = require("Trap")
local bait = require("Bait")
local zone = require("Zone")

local mouse = {}
mouse.baits = {}
mouse.traps = {}
mouse.zones = {}

--- ---------------------- Start mouse Default values -------------------------------

--                  ** BAIT **
local apple = 35
local cheese = 60
local chocolate = 30
local orange = 35
local peanutButter = 40
local processedCheese = 55
local tomato = 35

--                  ** ZONE **
local deepForest = 10
local farmLand = 60
local forest = 10
local townZone = 50
local trailerPark = 60
local vegetation = 20

--                  ** TRAP **
local trapMouse = 30

--                  ** SIZE ANIMALS **
local minSize = 1
local maxSize = 10

--                  ** QUALCOSA **
mouse.type = "mouse";
-- after how many hour the animal will start to destroy the cage/escape
mouse.strength = 24;
-- item given to the player
mouse.item = "Base.DeadMouse";
-- hour this animal will be out and when you can catch it
mouse.minHour = 0;
mouse.maxHour = 0;

--- ---------------------- Start Set Multiplier -------------------

--- **Set Bait Multiplier**
---@param multiplier int
local function setBaitMultiplier(multiplier)
    bait.setApple(apple * multiplier)
    bait.setCheese(cheese * multiplier)
    bait.setChocolate(chocolate * multiplier)
    bait.setOrange(orange * multiplier)
    bait.setPeanutButter(peanutButter * multiplier)
    bait.setProcessedCheese(processedCheese * multiplier)
    bait.setTomato(tomato * multiplier)
end

--- **Set Trap Multiplier**
---@param multiplier int
local function setTrapMultiplier(multiplier)
    trap.setTrapMouse(trapMouse * multiplier)
end

--- **Set Zone Multiplier**
---@param multiplier int
local function setZoneMultiplier(multiplier)
    zone.setDeepForest(deepForest * multiplier)
    zone.setFarmLand(farmLand * multiplier)
    zone.setForest(forest * multiplier)
    zone.setTownZone(townZone * multiplier)
    zone.setTrailerPark(trailerPark * multiplier)
    zone.setVegetation(vegetation * multiplier)
end

--- **Set "size" Multiplier**
--- Min and max "size" (understand hunger reduction) of the animal
---@param multiplier int
local function setSizeAnimalMultiplier(multiplier)
    mouse.minSize = minSize * multiplier;
    mouse.maxSize = maxSize * multiplier;
end

--- ---------------------- Start table bait/trap/zone -------------

--- **Create Bait**
---@param baitEnum Enum
---@param bait_ string
local function createBait(baitEnum, bait_)
    mouse.baits[baitEnum] = bait_
end

--- **Create Trap**
---@param trapEnum Enum
---@param trap_ string
local function createTrap(trapEnum, trap_)
    mouse.traps[trapEnum] = trap_
end
--
--- **Create Zone**
---@param zoneEnum Enum
---@param zone_ string
local function createZone(zoneEnum, zone_)
    mouse.zones[zoneEnum] = zone_
end

--- ---------------------- Start init Bait -------------------
--- **Init Bait**
local function initBait()
    createBait(bait.bait.APPLE, bait.getApple())
    createBait(bait.bait.BANANA, bait.getBanana())
    createBait(bait.bait.BELL_PEPPER, bait.getBellPepper())
    createBait(bait.bait.CABBAGE, bait.getCabbage())
    createBait(bait.bait.CARROTS, bait.getCarrots())
    createBait(bait.bait.CORN, bait.getCorn())
    createBait(bait.bait.LETTUCE, bait.getLettuce())
    createBait(bait.bait.PEACH, bait.getPeach())
    createBait(bait.bait.POTATO, bait.getPotato())
    createBait(bait.bait.TOMATO, bait.getTomato())
end

--- **Init Trap**
local function initTrap()
    createTrap(trap.trap.BOX, trap.getTrapBox())
    createTrap(trap.trap.CAGE, trap.getTrapCage())
    createTrap(trap.trap.CRATE, trap.getTrapCrate())
    createTrap(trap.trap.SNARE, trap.getTrapSnare())
end

--- **Init Zone**
local function initZone()
    createZone(zone.zone.DEEP_FOREST, zone.getDeepForest())
    createZone(zone.zone.FOREST, zone.getForest())
    createZone(zone.zone.TOWN_ZONE, zone.getTownZone())
    createZone(zone.zone.TRAILER_PARK, zone.getTrailerPark())
    createZone(zone.zone.VEGETATION, zone.getVegetation())
end


--- **Init rabbit**
---@param value int
---@return table rabbit
local function init()
    local multiplier = SandboxVars.TrappingSurvival.Multiplier

    --                  ** MULTIPLIER **
    setBaitMultiplier(multiplier)
    setTrapMultiplier(multiplier)
    setZoneMultiplier(multiplier)
    setSizeAnimalMultiplier(multiplier)

    --                  ** RABBIT BAIT/TRAP/ZONE **
    initBait()
    initTrap()
    initZone()

end

---**Get Mouse**
---@return table Mouse
function getMouse()
    init()
    return mouse
end
]]
