--[[
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 09/08/23 09:41
---

-- SteamLibrary/steamapps/common/ProjectZomboid/projectzomboid/media/lua/server/Traps/TrapDefinition.lua

--local trap = require("server/Trap")
--local bait = require("server/Bait")
--local zone = require("server/Zone")

local trap = require("Trap")
local bait = require("Bait")
local zone = require("Zone")

local squirrel = {}
squirrel.baits = {}
squirrel.traps = {}
squirrel.zones = {}

--- ---------------------- Start Squirrel Default values -------------------------------

--                  ** BAIT **
local apple = 40
local bellPepper = 30
local cereal = 45
local corn = 40
local orange = 40
local peach = 35
local peanutButter = 45
local peanuts = 40
local popcorn = 40

--                  ** ZONE **
local deepForest = 15
local forest = 12
local townZone = 2
local trailerPark = 2
local vegetation = 10

--                  ** TRAP **
local trapBox = 25
local trapCage = 40
local trapCrate = 30
local trapSnare = 30

--                  ** SIZE ANIMALS **
local minSize = 10
local maxSize = 60

--                  ** QUALCOSA **
squirrel.type = "rabbit";
-- after how many hour the animal will start to destroy the cage/escape
squirrel.strength = 24;
-- item given to the player
squirrel.item = "Base.DeadRabbit";
-- hour this animal will be out and when you can catch it
squirrel.minHour = 19;
squirrel.maxHour = 5;

--- ---------------------- Start Set Multiplier -------------------

--- **Set Bait Multiplier**
---@param multiplier int
local function setBaitMultiplier(multiplier)
    bait.setApple(apple * multiplier)
    bait.setBellPepper(bellPepper * multiplier)
    bait.setCereal(cereal * multiplier)
    bait.setCorn(corn * multiplier)
    bait.setOrange(orange * multiplier)
    bait.setPeach(peach * multiplier)
    bait.setPeanutButter(peanutButter * multiplier)
    bait.setPeanuts(peanuts * multiplier)
    bait.setPopcorn(popcorn * multiplier)
end

--- **Set Trap Multiplier**
---@param multiplier int
local function setTrapMultiplier(multiplier)
    trap.setTrapBox( trapBox * multiplier)
    trap.setTrapCage(trapCage * multiplier)
    trap.setTrapCrate(trapCrate * multiplier)
    trap.setTrapSnare(trapSnare * multiplier)
end

--- **Set Zone Multiplier**
---@param multiplier int
local function setZoneMultiplier(multiplier)
    zone.setDeepForest( deepForest * multiplier)
    zone.setForest(forest * multiplier)
    zone.setTownZone(townZone * multiplier)
    zone.setTrailerPark(trailerPark * multiplier)
    zone.setVegetation(vegetation * multiplier)
end

--- **Set "size" Multiplier**
--- Min and max "size" (understand hunger reduction) of the animal
---@param multiplier int
local function setSizeAnimalMultiplier(multiplier)
    squirrel.minSize = minSize * multiplier;
    squirrel.maxSize = maxSize * multiplier;
end

--- ---------------------- Start table bait/trap/zone -------------

--- **Create Bait**
---@param baitEnum Enum
---@param bait_ string
local function createBait(baitEnum, bait_)
    squirrel.baits[baitEnum] = bait_
end

--- **Create Trap**
---@param trapEnum Enum
---@param trap_ string
local function createTrap(trapEnum, trap_)
    squirrel.traps[trapEnum] = trap_
end
--
--- **Create Zone**
---@param zoneEnum Enum
---@param zone_ string
local function createZone(zoneEnum, zone_)
    squirrel.zones[zoneEnum] = zone_
end

--- ---------------------- Start init Bait -------------------
--- **Init Bait**
local function initBait()
    createBait(bait.bait.APPLE, bait.getApple())
    createBait(bait.bait.BELL_PEPPER, bait.getBellPepper())
    createBait(bait.bait.CEREAL, bait.getCereal())
    createBait(bait.bait.CORN, bait.getCorn())
    createBait(bait.bait.ORANGE, bait.getOrange())
    createBait(bait.bait.PEACH, bait.getPeach())
    createBait(bait.bait.PEANUT_BUTTER, bait.getPeanutButter())
    createBait(bait.bait.PEANUTS, bait.getPeanuts())
    createBait(bait.bait.POPCORN, bait.getPopcorn())
end

--- **Init Trap**
local function initTrap()
    createTrap(trap.trap.BOX, trap.getTrapBox())
    createTrap(trap.trap.CAGE, trap.getTrapCage())
    createTrap(trap.trap.CRATE, trap.getTrapCrate())
    createTrap(trap.trap.SNARE, trap.getTrapSnare())
end

--- **Init Zone**
local function initZone()
    createZone(zone.zone.DEEP_FOREST, zone.getDeepForest())
    createZone(zone.zone.FOREST, zone.getForest())
    createZone(zone.zone.TOWN_ZONE, zone.getTownZone())
    createZone(zone.zone.TRAILER_PARK, zone.getTrailerPark())
    createZone(zone.zone.VEGETATION, zone.getVegetation())
end


--- **Init rabbit**
---@param value int
---@return table rabbit
local function init()
    local multiplier = SandboxVars.TrappingSurvival.Multiplier

    --                  ** MULTIPLIER **
    setBaitMultiplier(multiplier)
    setTrapMultiplier(multiplier)
    setZoneMultiplier(multiplier)
    setSizeAnimalMultiplier(multiplier)

    --                  ** RABBIT BAIT/TRAP/ZONE **
    initBait()
    initTrap()
    initZone()

end

---**Get Squirrel**
---@return table Squirrel
function getSquirrel()
    init()
    return squirrel
end
]]
