---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 26/04/23 17:41
---

 --local trapping = require("lua/server/TrappingDB")
local trapping = require("Contenitore.TrappingDB") --

---@param character IsoGameCharacter
local function key34(character, key)
    if key == 34 then -- <<<< g
        print("Key = g > Sandbox \n")
        print(SandboxVars.TrapCage.Multiplier)
    end
end

---@param character IsoGameCharacter
local function key35(character, key)
    if key == 35 then -- <<< h
        print("Key = h > error \n")

    end
end

---@param character IsoGameCharacter
local function key36(character, key)
    if key == 36 then -- <<<< j
        print("Key = j > BAIT \n")

        local baitX = {}
        --- **Enum Bait**
        baitX.bait = {
            APPLE = trapping.bait.APPLE,
            BANANA = trapping.bait.BANANA,
            BELL_PEPPER = trapping.bait.BELL_PEPPER,
            CABBAGE = trapping.bait.CABBAGE,
            CARROTS = trapping.bait.CARROTS,
            CORN = trapping.bait.CORN,
            LETTUCE = trapping.bait.LETTUCE,
            PEACH = trapping.bait.PEACH,
            POTATO = trapping.bait.POTATO,
            TOMATO = trapping.bait.TOMATO,
        }
        print(baitX.bait.APPLE)
    end
end

---@param character IsoGameCharacter
local function key37(character, key)
    if key == 37 then -- <<<< k
        print("Key = k > delete \n")
        character:die()
    end
end

---@param character IsoGameCharacter
local function key16(character, key)
    if key == 16 then -- <<<< q

    end
end

---@param character IsoGameCharacter
local function key17(character, key)
    if key == 17 then -- <<<< w
        print("Key = w >  \n")

    end
end

---@param character IsoGameCharacter
local function key18(character, key)
    if key == 18 then -- <<<< e
        print("Key = e >  \n")

    end
end

local function onCustomUIKeyPressed(key)
    local character = getPlayer()

    key16(character, key)
    key17(character, key)
    key18(character, key)
    key34(character, key)
    key35(character, key)
    key36(character, key)
    key37(character, key)
end

-- ------------------------------------------------------------
-- ------------------------------------------------------------

local function OnGameStart()

end

-- Events.OnGameStart.Add(OnGameStart)
Events.OnCustomUIKeyPressed.Add(onCustomUIKeyPressed)
