---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 03/08/23 09:04
---

---@class Bait

--local trapping = require("server/TrappingDB")
--local trapping = require("TrappingDB")
local Bait = {}

local apple
local baconBits
local banana
local bread
local breadSlices
local bellPepper
local cabbage
local carrots
local cereal
local cheese
local chocolate
local cockroach
local corn
local cricket
local grasshopper
local lettuce
local orange
local peach
local peanut_butter
local peanuts
local processed_cheese
local popcorn
local potato
local tomato
local worm

--- **Enum Bait**
Bait.bait = {
    APPLE = "Base.Apple",
    BACONBITS = "farming.BaconBits",
    BANANA = "Base.Banana",
    BREAD = "Base.Bread",
    BREAD_SLICES = "Base.BreadSlices",
    BELL_PEPPER = "Base.BellPepper",
    CABBAGE = "farming.Cabbage",
    CARROTS = "Base.Carrots",
    CEREAL = "Base.Cereal",
    CHEESE = "Base.Cheese",
    CHOCOLATE = "Base.Chocolate",
    COCKROACH = "Base.Cockroach",
    CORN = "Base.Corn",
    CRICKET = "Base.Cricket",
    GRASSHOPPER = "Base.Grasshopper",
    LETTUCE = "Base.Lettuce",
    ORANGE = "Base.Orange",
    PEANUT_BUTTER = "Base.PeanutButter",
    PEANUTS = "Base.Peanuts",
    PROCESSED_CHEESE = "Base.Processedcheese",
    POPCORN = "Base.Popcorn",
    POTATO = "farming.Potato",
    TOMATO = "farming.Tomato",
    WORM = "Base.Worm",
}

--- **Set Apple**
---@param apple_ int
function Bait.setApple(apple_)
    if apple_ < 0 then
        print("ERROR : APPLE " .. tostring(apple_))
        return
    end

    apple = apple_
end

--- **Get Apple**
---@return int apple
function Bait.getApple()
    return apple
end

--- **Set Bacon Bits**
---@param baconBits_ int
function Bait.setBaconBits(baconBits_)
    if baconBits_ < 0 then
        print("ERROR : BACON_BITS " .. tostring(baconBits_))
        return
    end

    baconBits = baconBits_
end

--- **Get Bacon Bits**
---@return int baconBits
function Bait.getBaconBits()
    return baconBits
end

--- **Set Banana**
---@param banana_ int
function Bait.setBanana(banana_)
    if banana_ < 0 then
        print("ERROR : BANANA " .. tostring(banana_))
        return
    end

    banana = banana_
end

--- **Get Banana**
---@return int banana
function Bait.getBanana()
    return banana
end

--- **Set Bread**
---@param bread_ int
function Bait.setBread(bread_)
    if bread_ < 0 then
        print("ERROR : BREAD " .. tostring(bread_))
        return
    end

    bread = bread_
end

--- **Get Bread**
---@return int bread
function Bait.getBread()
    return bread
end

--- **Set Bread Slices**
---@param breadSlices_ int
function Bait.setBreadSlices(breadSlices_)
    if breadSlices_ < 0 then
        print("ERROR : BREAD_SLICES " .. tostring(breadSlices_))
        return
    end

    breadSlices = breadSlices_
end

--- **Get Bread Slice**
---@return int bread_slices
function Bait.getBreadSlice()
    return breadSlices
end

--- **Set Bell Pepper**
---@param bellPepper_ int
function Bait.setBellPepper(bellPepper_)
    if bellPepper_ < 0 then
        print("ERROR : BELL_PEPPER " .. tostring(bellPepper_))
        return
    end

    bellPepper = bellPepper_
end

--- **Get Bell Pepper**
---@return int bell_pepper
function Bait.getBellPepper()
    return bellPepper
end

--- **Set Cabbage**
---@param cabbage_ int
function Bait.setCabbage(cabbage_)
    if cabbage_ < 0 then
        print("ERROR : CABBAGE " .. tostring(cabbage_))
        return
    end

    cabbage = cabbage_
end

--- **Get Cabbage**
---@return int cabbage
function Bait.getCabbage()
    return cabbage
end

--- **Set Carrots**
---@param carrots_ int
function Bait.setCarrots(carrots_)
    if carrots_ < 0 then
        print("ERROR : CARROTS " .. tostring(carrots_))
        return
    end

    carrots = carrots_
end

--- **Get Carrots**
---@return int carrots
function Bait.getCarrots()
    return carrots
end

--- **Set Cereal**
---@param cereal_ int
function Bait.setCereal(cereal_)
    if cereal_ < 0 then
        print("ERROR : CEREAL " .. tostring(cereal_))
        return
    end

    cereal = cereal_
end

--- **Get Cereal**
---@return int cereal
function Bait.getCereal()
    return cereal
end

--- **Set Cheese**
---@param cheese_ int
function Bait.setCheese(cheese_)
    if cheese_ < 0 then
        print("ERROR : CHEESE " .. tostring(cheese_))
        return
    end

    cheese = cheese_
end

--- **Get Cheese**
---@return int cheese
function Bait.getCheese()
    return cheese
end

--- **Set Chocolate**
---@param chocolate_ int
function Bait.setChocolate(chocolate_)
    if chocolate_ < 0 then
        print("ERROR : CHOCOLATE " .. tostring(chocolate_))
        return
    end

    chocolate = chocolate_
end

--- **Get Chocolate**
---@return int chocolate
function Bait.getChocolate()
    return chocolate
end

--- **Set Cockroach**
---@param cockroach_ int
function Bait.setCockroach(cockroach_)
    if cockroach_ < 0 then
        print("ERROR : COCKROACH " .. tostring(cockroach_))
        return
    end

    cockroach = cockroach_
end

--- **Get Cockroach**
---@return int cockroach
function Bait.getCockroach()
    return cockroach
end

--- **Set Corn**
---@param corn_ int
function Bait.setCorn(corn_)
    if corn_ < 0 then
        print("ERROR : CORN " .. tostring(corn_))
        return
    end

    corn = corn_
end

--- **Get Corn**
---@return int corn
function Bait.getCorn()
    return corn
end

--- **Set Cricket**
---@param cricket_ int
function Bait.setCricket(cricket_)
    if cricket_ < 0 then
        print("ERROR : CRICKET " .. tostring(cricket_))
        return
    end

    cricket = cricket_
end

--- **Get Cricket**
---@return int cricket
function Bait.getCricket()
    return cricket
end

--- **Set Grasshopper**
---@param grasshopper_ int
function Bait.setGrasshopper(grasshopper_)
    if grasshopper_ < 0 then
        print("ERROR : GRASSHOPPER " .. tostring(grasshopper_))
        return
    end

    grasshopper = grasshopper_
end

--- **Get Grasshopper**
---@return int grasshopper
function Bait.getGrasshopper()
    return grasshopper
end

--- **Set Lettuce**
---@param lettuce_ int
function Bait.setLettuce(lettuce_)
    if lettuce_ < 0 then
        print("ERROR : LETTUCE " .. tostring(lettuce_))
        return
    end

    lettuce = lettuce_
end

--- **Get Lettuce**
---@return int lettuce
function Bait.getLettuce()
    return lettuce
end

--- **Set Orange**
---@param orange_ int
function Bait.setOrange(orange_)
    if orange_ < 0 then
        print("ERROR : ORANGE " .. tostring(orange_))
        return
    end

    orange = orange_
end

--- **Get Orange**
---@return int orange
function Bait.getOrange()
    return orange
end

--- **Set Peach**
---@param peach_ int
function Bait.setPeach(peach_)
    if peach < 0 then
        print("ERROR : PEACH " .. tostring(peach_))
        return
    end

    peach = peach_
end

--- **Get Peach**
---@return int Peach
function Bait.getPeach()
    return peach
end


--- **Set Peanut Butter**
---@param peanutButter_ int
function Bait.setPeanutButter(peanutButter_)
    if peanutButter_ < 0 then
        print("ERROR : PEANUTBUTTER " .. tostring(peanutButter_))
        return
    end

    peanut_butter = peanutButter_
end

--- **Get Peanut Butter**
---@return int peanutButter
function Bait.getPeanutButter()
    return peanut_butter
end

--- **Set Peanuts**
---@param peanuts_ int
function Bait.setPeanuts(peanuts_)
    if peanuts_ < 0 then
        print("ERROR : PEANUTS " .. tostring(peanuts_))
        return
    end

    peanuts = peanuts_
end

--- **Get Peanuts**
---@return int peanuts
function Bait.getPeanuts()
    return peanuts
end

--- **Set Processed Cheese**
---@param processedCheese_ int
function Bait.setProcessedCheese(processedCheese_)
    if processedCheese_ < 0 then
        print("ERROR : PROCESSED_CHEESE " .. tostring(processedCheese_))
        return
    end

    processed_cheese = processedCheese_
end

--- **Get Processed Cheese**
---@return int processedCheese
function Bait.getProcessedCheese()
    return processed_cheese
end

--- **Set Popcorn**
---@param popcorn_ int
function Bait.setPopcorn(popcorn_)
    if popcorn_ < 0 then
        print("ERROR : POPCORN " .. tostring(popcorn_))
        return
    end

    popcorn = popcorn_
end

--- **Get Popcorn**
---@return int popcorn
function Bait.getPopcorn()
    return popcorn
end

--- **Set Potato**
---@param potato_ int
function Bait.setPotato(potato_)
    if potato_ < 0 then
        print("ERROR : POTATO " .. tostring(potato_))
        return
    end

    potato = potato_
end

--- **Get Potato**
---@return int potato
function Bait.getPotato()
    return potato
end

--- **Set Tomato**
---@param tomato_ int
function Bait.setTomato(tomato_)
    if tomato_ < 0 then
        print("ERROR : TOMATO " .. tostring(tomato_))
        return
    end

    tomato = tomato_
end

--- **Get Tomato**
---@return int tomato
function Bait.getTomato()
    return tomato
end

--- **Set Worm**
---@param worm_ int
function Bait.setWorm(worm_)
    if worm_ < 0 then
        print("ERROR : WORM " .. tostring(worm_))
        return
    end

    worm = worm_
end

--- **Get Worm**
---@return int worm
function Bait.getWorm()
    return worm
end

return Bait
