---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 09/08/23 09:41
---

-- SteamLibrary/steamapps/common/ProjectZomboid/projectzomboid/media/lua/server/Traps/TrapDefinition.lua

--local trap = require("server/Trap")
--local bait = require("server/Bait")
--local zone = require("server/Zone")

local trap = require("Trap")
local bait = require("Bait")
local zone = require("Zone")

local bird = {}
bird.baits = {}
bird.traps = {}
bird.zones = {}

--- ---------------------- Start bird Default values -------------------------------

--                  ** BAIT **

local bread = 50
local breadSlices = 50
local cereal = 45
local cockroach = 50
local corn = 45
local cricket = 50
local grasshopper = 50
local worm = 50

--                  ** ZONE **
local deepForest = 20
local farmLand = 35 -- <<<<<<<<<<<<<<<<<<<<<<<<<<
local forest = 20
local townZone = 30
local trailerPark = 20
local vegetation = 30

--                  ** TRAP **
local trapStick = 40

--                  ** SIZE ANIMALS **
local minSize = 2
local maxSize = 32

--                  ** QUALCOSA **
bird.type = "bird";
-- after how many hour the animal will start to destroy the cage/escape
bird.strength = 24;
-- item given to the player
bird.item = "Base.DeadBird";
-- hour this animal will be out and when you can catch it
bird.minHour = 0;
bird.maxHour = 0;

--- ---------------------- Start Set Multiplier -------------------

--- **Set Bait Multiplier**
---@param multiplier int
local function setBaitMultiplier(multiplier)
    bait.setBread( bread * multiplier)
    bait.setBreadSlices( breadSlices * multiplier)
    bait.setCereal( cereal * multiplier)
    bait.setCockroach( cockroach * multiplier)
    bait.setCorn( corn * multiplier)
    bait.setCricket( cricket * multiplier)
    bait.setGrasshopper( grasshopper * multiplier)
    bait.setWorm( worm * multiplier)
end

--- **Set Trap Multiplier**
---@param multiplier int
local function setTrapMultiplier(multiplier)
    trap.setTrapStick( trapStick * multiplier)
end

--- **Set Zone Multiplier**
---@param multiplier int
local function setZoneMultiplier(multiplier)
    zone.setDeepForest( deepForest * multiplier)
    zone.setFarmLand(farmLand * multiplier)
    zone.setForest(forest * multiplier)
    zone.setTownZone(townZone * multiplier)
    zone.setTrailerPark(trailerPark * multiplier)
    zone.setVegetation(vegetation * multiplier)
end

--- **Set "size" Multiplier**
--- Min and max "size" (understand hunger reduction) of the animal
---@param multiplier int
local function setSizeAnimalMultiplier(multiplier)
    bird.minSize = minSize * multiplier;
    bird.maxSize = maxSize * multiplier;
end

--- ---------------------- Start table bait/trap/zone -------------

--- **Create Bait**
---@param baitEnum Enum
---@param bait_ string
local function createBait(baitEnum, bait_)
    bird.baits[baitEnum] = bait_
end

--- **Create Trap**
---@param trapEnum Enum
---@param trap_ string
local function createTrap(trapEnum, trap_)
    bird.traps[trapEnum] = trap_
end

--- **Create Zone**
---@param zoneEnum Enum
---@param zone_ string
local function createZone(zoneEnum, zone_)
    bird.zones[zoneEnum] = zone_
end

--- ---------------------- Start init Bait -------------------
--- **Init Bait**
local function initBait()
    createBait(bait.bait.BREAD, bait.getBread())
    createBait(bait.bait.BREAD_SLICES, bait.getBreadSlices())
    createBait(bait.bait.CEREAL, bait.getCereal())
    createBait(bait.bait.COCKROACH, bait.getCockroach())
    createBait(bait.bait.CORN, bait.getCorn())
    createBait(bait.bait.CRICKET, bait.getCricket())
    createBait(bait.bait.GRASSHOPPER, bait.getGrasshopper())
    createBait(bait.bait.WORM, bait.getWorm())
end

--- **Init Trap**
local function initTrap()
    createTrap(trap.trap.TRAP_STICK, trap.getTrapStick())
end

--- **Init Zone**
local function initZone()
    createZone(zone.zone.DEEP_FOREST, zone.getDeepForest())
    createZone(zone.zone.FARM_LAND, zone.getFarmLand())
    createZone(zone.zone.FOREST, zone.getForest())
    createZone(zone.zone.TOWN_ZONE, zone.getTownZone())
    createZone(zone.zone.TRAILER_PARK, zone.getTrailerPark())
    createZone(zone.zone.VEGETATION, zone.getVegetation())
end

--- **Init rabbit**
---@param value int
---@return table rabbit
local function init()
    local multiplier = SandboxVars.TrapCage.Multiplier

    --                  ** MULTIPLIER **
    setBaitMultiplier(multiplier)
    setTrapMultiplier(multiplier)
    setZoneMultiplier(multiplier)
    setSizeAnimalMultiplier(multiplier)

    --                  ** RABBIT BAIT/TRAP/ZONE **
    initBait()
    initTrap()
    initZone()

end

---**Get Bird**
---@return table Bird
function getBird()
    init()
    return bird
end
