---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 13/08/23 23:14
---

-- https://pzwiki.net/wiki/Trapping
-- SteamLibrary/steamapps/common/ProjectZomboid/projectzomboid/media/lua/server/Traps/TrapDefinition.lua

---@class Bird

local creatureFactory = require("CreatureFactory")
local bird = {}

local trap = require("Trap")
local bait = require("Bait")
local zone = require("Zone")

--- ---------------------- Start Bird Default values -------------------------------

--                  ** BAIT **

local bread = 50
local breadSlices = 50
local cereal = 45
local cockroach = 50
local corn = 45
local cricket = 50
local grasshopper = 50
local worm = 50

--                  ** ZONE **
local deepForest = 20
local farmLand = 35
local forest = 20
local townZone = 30
local trailerPark = 20
local vegetation = 30

--                  ** TRAP **
local trapStick = 40

--                  ** ANIMALS **
-- Type of animal
local type = "bird"

-- after how many hour the animal will start to destroy the cage/escape
local strength = 24

-- item given to the player
local item = "Base.DeadBird"

-- hour this animal will be out and when you can catch it
local minHour = 0
local maxHour = 0

-- min and max "size" (understand hunger reduction) of the animal
local minSize = 2
local maxSize = 32

--- ---------------------- Set Multiplier -------------------

--- **Set Bait Multiplier**
---@param multiplier int
local function setBaitMultiplier(multiplier)
    bait.setBread( bread * multiplier)
    bait.setBreadSlices( breadSlices * multiplier)
    bait.setCereal( cereal * multiplier)
    bait.setCockroach( cockroach * multiplier)
    bait.setCorn( corn * multiplier)
    bait.setCricket( cricket * multiplier)
    bait.setGrasshopper( grasshopper * multiplier)
    bait.setWorm( worm * multiplier)
end

--- **Set Trap Multiplier**
---@param multiplier int
local function setTrapMultiplier(multiplier)
    trap.setTrapStick( trapStick * multiplier)
end

--- **Set Zone Multiplier**
---@param multiplier int
local function setZoneMultiplier(multiplier)
    zone.setDeepForest( deepForest * multiplier)
    zone.setFarmLand(farmLand * multiplier)
    zone.setForest(forest * multiplier)
    zone.setTownZone(townZone * multiplier)
    zone.setTrailerPark(trailerPark * multiplier)
    zone.setVegetation(vegetation * multiplier)
end

--- **Set "size" Multiplier**
--- Min and max "size" (understand hunger reduction) of the animal
---@param multiplier int
local function setSizeAnimalMultiplier(multiplier)
    bird.minSize = minSize * multiplier;
    bird.maxSize = maxSize * multiplier;
end

--- ---------------------- Start init Bait -------------------

--- **Init Bait**
local function initBait()
    creatureFactory.createBait(bird, bait.bait.BREAD, bait.getBread())
    creatureFactory.createBait(bird, bait.bait.BREAD_SLICES, bait.getBreadSlices())
    creatureFactory.createBait(bird, bait.bait.CEREAL, bait.getCereal())
    creatureFactory.createBait(bird, bait.bait.COCKROACH, bait.getCockroach())
    creatureFactory.createBait(bird, bait.bait.CORN, bait.getCorn())
    creatureFactory.createBait(bird, bait.bait.CRICKET, bait.getCricket())
    creatureFactory.createBait(bird, bait.bait.GRASSHOPPER, bait.getGrasshopper())
    creatureFactory.createBait(bird, bait.bait.WORM, bait.getWorm())
end

--- **Init Trap**
local function initTrap()
    creatureFactory.createTrap(bird, trap.trap.TRAP_STICK, trap.getTrapStick())
end

--- **Init Zone**
local function initZone()
    creatureFactory.createZone(bird, zone.zone.DEEP_FOREST, zone.getDeepForest())
    creatureFactory.createZone(bird, zone.zone.FARM_LAND, zone.getFarmLand())
    creatureFactory.createZone(bird, zone.zone.FOREST, zone.getForest())
    creatureFactory.createZone(bird, zone.zone.TOWN_ZONE, zone.getTownZone())
    creatureFactory.createZone(bird, zone.zone.TRAILER_PARK, zone.getTrailerPark())
    creatureFactory.createZone(bird, zone.zone.VEGETATION, zone.getVegetation())
end

--- **Init**
local function init()
    local multiplier = SandboxVars.TrappingSurvival.Bird
    bird = creatureFactory.creature(type, strength, item, maxSize, minSize, minHour, maxHour)

    --                  ** MULTIPLIER **
    setBaitMultiplier(multiplier)
    setTrapMultiplier(multiplier)
    setZoneMultiplier(multiplier)
    -- setSizeAnimalMultiplier(multiplier)

    initBait()
    initTrap()
    initZone()
end

---**Get Bird**
---@return table Bird
function getBird()
    init()
    return bird
end

