---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 13/08/23 12:07
---

-- SteamLibrary/steamapps/common/ProjectZomboid/projectzomboid/media/lua/server/Traps/RabbitX04.lua

local CreatureFactory = {}

function CreatureFactory.creature(animal, strength, item, minSize, maxSize, minHour, maxHour)
    local creature = {}
    creature.baits = {}
    creature.traps = {}
    creature.zone = {} -- << !!!!!!!!!!!!!!!!!! It's a table, it would need an 's' !!!!!!!!!!!!!!!
    creature.type = animal
    creature.strength = strength
    creature.item = item
    creature.minSize = minSize
    creature.maxSize = maxSize
    creature.minHour = minHour
    creature.maxHour = maxHour
    return creature
end

--- ---------------------- Start table bait/trap/zone -------------

--- **Create Bait**
---@param baitEnum Enum
---@param bait_ string
function CreatureFactory.createBait(creature_, baitEnum, bait_)
    creature_.baits[baitEnum] = bait_
end

--- **Create Trap**
---@param trapEnum Enum
---@param trap_ string
function CreatureFactory.createTrap(creature_, trapEnum, trap_)
    creature_.traps[trapEnum] = trap_
end

--- **Create Zone**
---@param zoneEnum Enum
---@param zone_ string
function CreatureFactory.createZone(creature_, zoneEnum, zone_)
    creature_.zone[zoneEnum] = zone_
end

return CreatureFactory
