---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 13/08/23 23:14
---

--- ---------------------- Start Rabbit Default values -------------------------------

-- SteamLibrary/steamapps/common/ProjectZomboid/projectzomboid/media/lua/server/Traps/RabbitX04.lua

--local bait = require("server/Bait")
--local trap = require("server/Trap")
--local zone = require("server/Zone")

--local rabbit = require("media.lua.server.Creature")
local creatureFactory = require("CreatureFactory")
local rabbit = {}
Animals = {};

-----------------------------------------
--Traps = {}
--local cageTrap = {};
--cageTrap.type = "Base.TrapCage";
--cageTrap.sprite = "constructedobjects_01_8";
--cageTrap.northSprite = "constructedobjects_01_11";
--cageTrap.closedSprite = "constructedobjects_01_9";
--cageTrap.northClosedSprite = "constructedobjects_01_10";
--cageTrap.trapStrength = 100;
--cageTrap.destroyItem = { "Base.Wire", "Base.MetalPipe", "Base.MetalPipe", "Base.MetalPipe", "Base.SheetMetal", "Base.SheetMetal" };
--table.insert(Traps, cageTrap);

--------------------------------

local trap = require("Trap")
local bait = require("Bait")
local zone = require("Zone")

--                  ** BAIT **
local apple = 35
local banana = 35
local bellPepper = 40
local cabbage = 40
local carrots = 45
local corn = 35
local lettuce = 40
local peach = 35
local potato = 35
local tomato = 35

--                  ** ZONE **
local deepForest = 15
local forest = 12
local townZone = 2
local trailerPark = 2
local vegetation = 10

--                  ** TRAP **
local trapBox = 30
local trapCage = 40
local trapCrate = 30
local trapSnare = 30

--                  ** ANIMALS **
-- Type of animal
local type = "rabbit"

-- after how many hour the animal will start to destroy the cage/escape
local strength = 24

-- item given to the player
local item = "Base.DeadRabbit"

-- hour this animal will be out and when you can catch it
local minHour = 5 -- 18
local maxHour = 15 -- 8

-- min and max "size" (understand hunger reduction) of the animal
local minSize = 30
local maxSize = 100


--- **Set Bait Multiplier**
---@param multiplier int
local function setBaitMultiplier(multiplier)
    --bait.setPotato(potato * multiplier)

    bait.setApple(apple * multiplier)
    bait.setBanana(banana * multiplier)
    bait.setBellPepper(bellPepper * multiplier)
    bait.setCabbage(cabbage * multiplier)
    bait.setCarrots(carrots * multiplier)
    bait.setCorn(corn * multiplier)
    bait.setLettuce(lettuce * multiplier)
    bait.setPeach(peach * multiplier)
    bait.setPotato(potato * multiplier)
    bait.setTomato(tomato * multiplier)
end

--- **Set Trap Multiplier**
---@param multiplier int
local function setTrapMultiplier(multiplier)
    --trap.setTrapCage(trapCage * multiplier)

    trap.setTrapBox(trapBox * multiplier)
    trap.setTrapCage(trapCage * multiplier)
    trap.setTrapCrate(trapCrate * multiplier)
    trap.setTrapSnare(trapSnare * multiplier)
end

--- **Set Zone Multiplier**
---@param multiplier int
local function setZoneMultiplier(multiplier)
    --zone.setDeepForest( deepForest * multiplier)

    zone.setDeepForest( deepForest * multiplier)
    zone.setForest(forest * multiplier)
    zone.setTownZone(townZone * multiplier)
    zone.setTrailerPark(trailerPark * multiplier)
    zone.setVegetation(vegetation * multiplier)
end

--- **Set "size" Multiplier**
--- Min and max "size" (understand hunger reduction) of the animal
---@param multiplier int
local function setSizeAnimalMultiplier(multiplier)
    rabbit.minSize = minSize * multiplier;
    rabbit.maxSize = maxSize * multiplier;
end

--- ---------------------- Start init Bait -------------------
--- **Init Bait**
local function initBait()
--    creatureFactory.createBait(rabbit, bait.bait.POTATO, bait.getPotato())

    creatureFactory.createBait(rabbit, bait.bait.APPLE, bait.getApple())
    creatureFactory.createBait(rabbit, bait.bait.BANANA, bait.getBanana())
    creatureFactory.createBait(rabbit, bait.bait.BELL_PEPPER, bait.getBellPepper())
    creatureFactory.createBait(rabbit, bait.bait.CABBAGE, bait.getCabbage())
    creatureFactory.createBait(rabbit, bait.bait.CARROTS, bait.getCarrots())
    creatureFactory.createBait(rabbit, bait.bait.CORN, bait.getCorn())
    creatureFactory.createBait(rabbit, bait.bait.LETTUCE, bait.getLettuce())
    creatureFactory.createBait(rabbit, bait.bait.PEACH, bait.getPeach())
    creatureFactory.createBait(rabbit, bait.bait.POTATO, bait.getPotato())
    creatureFactory.createBait(rabbit, bait.bait.TOMATO, bait.getTomato())
end

--- **Init Trap**
local function initTrap()
    -- creatureFactory.createTrap(rabbit, trap.trap.CAGE, trap.getTrapCage())

    creatureFactory.createTrap(rabbit, trap.trap.BOX, trap.getTrapBox())
    creatureFactory.createTrap(rabbit, trap.trap.CAGE, trap.getTrapCage())
    creatureFactory.createTrap(rabbit, trap.trap.CRATE, trap.getTrapCrate())
    creatureFactory.createTrap(rabbit, trap.trap.SNARE, trap.getTrapSnare())
end

--- **Init Zone**
local function initZone()
--    creatureFactory.createZone(rabbit, zone.zone.DEEP_FOREST, zone.getDeepForest())

    creatureFactory.createZone(rabbit, zone.zone.DEEP_FOREST, zone.getDeepForest())
    creatureFactory.createZone(rabbit, zone.zone.FOREST, zone.getForest())
    creatureFactory.createZone(rabbit, zone.zone.TOWN_ZONE, zone.getTownZone())
    creatureFactory.createZone(rabbit, zone.zone.TRAILER_PARK, zone.getTrailerPark())
    creatureFactory.createZone(rabbit, zone.zone.VEGETATION, zone.getVegetation())
end

function init()
    local multiplier = SandboxVars.TrappingSurvival.Multiplier
    rabbit = creatureFactory.creature(type, strength, item, maxSize, minSize, minHour, maxHour)

    --                  ** MULTIPLIER **
    setBaitMultiplier(multiplier)
    setTrapMultiplier(multiplier)
    setZoneMultiplier(multiplier)
    setSizeAnimalMultiplier(multiplier)

    initBait()
    initTrap()
    initZone()

    table.insert(Animals, rabbit)
end

init()
