---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 09/08/23 09:41
---

-- SteamLibrary/steamapps/common/ProjectZomboid/projectzomboid/media/lua/server/Traps/TrapDefinition.lua

--local trap = require("server/Trap")
--local bait = require("server/Bait")
--local zone = require("server/Zone")

local trap = require("Trap")
local bait = require("Bait")
local zone = require("Zone")

local rat = {}
rat.baits = {}
rat.traps = {}
rat.zones = {}

--- ---------------------- Start mouse Default values -------------------------------

--                  ** BAIT **
local apple = 35
local cheese = 60
local chocolate = 30
local orange = 35
local peanutButter = 40
local processedCheese = 55
local tomato = 35

--                  ** ZONE **
local deepForest = 10
local farmLand = 50
local forest = 10
local townZone = 30
local trailerPark = 40
local vegetation = 20

--                  ** TRAP **
local trapMouse = 25

--                  ** SIZE ANIMALS **
local minSize = 5
local maxSize = 25

--                  ** QUALCOSA **
rat.type = "rat";
-- after how many hour the animal will start to destroy the cage/escape
rat.strength = 24;
-- item given to the player
rat.item = "Base.DeadRat";
-- hour this animal will be out and when you can catch it
rat.minHour = 0;
rat.maxHour = 0;

--- ---------------------- Start Set Multiplier -------------------

--- **Set Bait Multiplier**
---@param multiplier int
local function setBaitMultiplier(multiplier)
    bait.setApple(apple * multiplier)
    bait.setCheese(cheese * multiplier)
    bait.setChocolate(chocolate * multiplier)
    bait.setOrange(orange * multiplier)
    bait.setPeanutButter(peanutButter * multiplier)
    bait.setProcessedCheese(processedCheese * multiplier)
    bait.setTomato(tomato * multiplier)
end

--- **Set Trap Multiplier**
---@param multiplier int
local function setTrapMultiplier(multiplier)
    trap.setTrapMouse(trapMouse * multiplier)
end

--- **Set Zone Multiplier**
---@param multiplier int
local function setZoneMultiplier(multiplier)
    zone.setDeepForest(deepForest * multiplier)
    zone.setFarmLand(farmLand * multiplier)
    zone.setForest(forest * multiplier)
    zone.setTownZone(townZone * multiplier)
    zone.setTrailerPark(trailerPark * multiplier)
    zone.setVegetation(vegetation * multiplier)
end

--- **Set "size" Multiplier**
--- Min and max "size" (understand hunger reduction) of the animal
---@param multiplier int
local function setSizeAnimalMultiplier(multiplier)
    rat.minSize = minSize * multiplier;
    rat.maxSize = maxSize * multiplier;
end

--- ---------------------- Start table bait/trap/zone -------------

--- **Create Bait**
---@param baitEnum Enum
---@param bait_ string
local function createBait(baitEnum, bait_)
    rat.baits[baitEnum] = bait_
end

--- **Create Trap**
---@param trapEnum Enum
---@param trap_ string
local function createTrap(trapEnum, trap_)
    rat.traps[trapEnum] = trap_
end
--
--- **Create Zone**
---@param zoneEnum Enum
---@param zone_ string
local function createZone(zoneEnum, zone_)
    rat.zones[zoneEnum] = zone_
end

--- ---------------------- Start init Bait -------------------
--- **Init Bait**
local function initBait()
    createBait(bait.bait.APPLE, bait.getApple())
    createBait(bait.bait.CHEESE, bait.getCheese())
    createBait(bait.bait.CHOCOLATE, bait.getChocolate())
    createBait(bait.bait.ORANGE, bait.getOrange())
    createBait(bait.bait.PEANUT_BUTTER, bait.getPeanutButter())
    createBait(bait.bait.PROCESSED_CHEESE, bait.getProcessedCheese())
    createBait(bait.bait.TOMATO, bait.getTomato())
end

--- **Init Trap**
local function initTrap()
    createTrap(trap.trap.MOUSE, trap.getTrapMouse())
end

--- **Init Zone**
local function initZone()
    createZone(zone.zone.DEEP_FOREST, zone.getDeepForest())
    createZone(zone.zone.FOREST, zone.getForest())
    createZone(zone.zone.TOWN_ZONE, zone.getTownZone())
    createZone(zone.zone.TRAILER_PARK, zone.getTrailerPark())
    createZone(zone.zone.VEGETATION, zone.getVegetation())
end


--- **Init Rat**
---@param value int
---@return table Rat
local function init()
    local multiplier = SandboxVars.TrapCage.Multiplier

    --                  ** MULTIPLIER **
    setBaitMultiplier(multiplier)
    setTrapMultiplier(multiplier)
    setZoneMultiplier(multiplier)
    setSizeAnimalMultiplier(multiplier)

    --                  ** RAT BAIT/TRAP/ZONE **
    initBait()
    initTrap()
    initZone()

end

---**Get Rat**
---@return table Mouse
function getRat()
    init()
    return rat
end
