---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 13/08/23 23:14
---

-- https://pzwiki.net/wiki/Trapping
-- SteamLibrary/steamapps/common/ProjectZomboid/projectzomboid/media/lua/server/Traps/TrapDefinition.lua

---@class Squirrel

--- ---------------------- Start Squirrel Default values -------------------------------

local creatureFactory = require("CreatureFactory")
local squirrel = {}

local trap = require("Trap")
local bait = require("Bait")
local zone = require("Zone")

--                  ** BAIT **

local apple = 40
local bellPepper = 30
local cereal = 45
local corn = 40
local orange = 40
local lettuce = 40
local peach = 35
local peanutButter = 45
local peanuts = 40
local popcorn = 40

--                  ** ZONE **
local deepForest = 15
local forest = 12
local townZone = 2
local trailerPark = 2
local vegetation = 10

--                  ** TRAP **
local trapBox = 25
local trapCage = 40
local trapCrate = 30
local trapSnare = 30

--                  ** ANIMALS **
-- Type of animal
local type = "squirrel"

-- after how many hour the animal will start to destroy the cage/escape
local strength = 24

-- item given to the player
local item = "Base.DeadSquirrel"

-- hour this animal will be out and when you can catch it
local minHour = 18
local maxHour = 8

-- min and max "size" (understand hunger reduction) of the animal
local minSize = 30
local maxSize = 100

--- ---------------------- Set Multiplier -------------------

--- **Set Bait Multiplier**
---@param multiplier int
local function setBaitMultiplier(multiplier)
    bait.setApple(apple * multiplier)
    bait.setBellPepper(bellPepper * multiplier)
    bait.setCereal(cereal * multiplier)
    bait.setCorn(corn * multiplier)
    bait.setOrange(orange * multiplier)
    bait.setLettuce(lettuce * multiplier)
    bait.setPeach(peach * multiplier)
    bait.setPeanutButter(peanutButter * multiplier)
    bait.setPeanuts(peanuts * multiplier)
    bait.setPopcorn(popcorn * multiplier)
end

--- **Set Trap Multiplier**
---@param multiplier int
local function setTrapMultiplier(multiplier)
    trap.setTrapBox(trapBox * multiplier)
    trap.setTrapCage(trapCage * multiplier)
    trap.setTrapCrate(trapCrate * multiplier)
    trap.setTrapSnare(trapSnare * multiplier)
end

--- **Set Zone Multiplier**
---@param multiplier int
local function setZoneMultiplier(multiplier)
    zone.setDeepForest( deepForest * multiplier)
    zone.setForest(forest * multiplier)
    zone.setTownZone(townZone * multiplier)
    zone.setTrailerPark(trailerPark * multiplier)
    zone.setVegetation(vegetation * multiplier)
end

--- **Set "size" Multiplier**
--- Min and max "size" (understand hunger reduction) of the animal
---@param multiplier int
local function setSizeAnimalMultiplier(multiplier)
    squirrel.minSize = minSize * multiplier;
    squirrel.maxSize = maxSize * multiplier;
end

--- ---------------------- Start init Bait -------------------

--- **Init Bait**
local function initBait()
    creatureFactory.createBait(squirrel, bait.bait.APPLE, bait.getApple())
    creatureFactory.createBait(squirrel, bait.bait.BELL_PEPPER, bait.getBellPepper())
    creatureFactory.createBait(squirrel, bait.bait.CEREAL, bait.getCereal())
    creatureFactory.createBait(squirrel, bait.bait.CORN, bait.getCorn())
    creatureFactory.createBait(squirrel, bait.bait.ORANGE, bait.getOrange())
    creatureFactory.createBait(squirrel, bait.bait.LETTUCE, bait.getLettuce())
    creatureFactory.createBait(squirrel, bait.bait.PEACH, bait.getPeach())
    creatureFactory.createBait(squirrel, bait.bait.PEANUT_BUTTER, bait.getPeanutButter())
    creatureFactory.createBait(squirrel, bait.bait.PEANUTS, bait.getPeanuts())
    creatureFactory.createBait(squirrel, bait.bait.POPCORN, bait.getPopcorn())
end

--- **Init Trap**
local function initTrap()
    creatureFactory.createTrap(squirrel, trap.trap.BOX, trap.getTrapBox())
    creatureFactory.createTrap(squirrel, trap.trap.CAGE, trap.getTrapCage())
    creatureFactory.createTrap(squirrel, trap.trap.CRATE, trap.getTrapCrate())
    creatureFactory.createTrap(squirrel, trap.trap.SNARE, trap.getTrapSnare())
end

--- **Init Zone**
local function initZone()
    creatureFactory.createZone(squirrel, zone.zone.DEEP_FOREST, zone.getDeepForest())
    creatureFactory.createZone(squirrel, zone.zone.FOREST, zone.getForest())
    creatureFactory.createZone(squirrel, zone.zone.TOWN_ZONE, zone.getTownZone())
    creatureFactory.createZone(squirrel, zone.zone.TRAILER_PARK, zone.getTrailerPark())
    creatureFactory.createZone(squirrel, zone.zone.VEGETATION, zone.getVegetation())
end

--- **Init**
local function init()
    local multiplier = SandboxVars.TrappingSurvival.Squirrel
    squirrel = creatureFactory.creature(type, strength, item, maxSize, minSize, minHour, maxHour)

    --                  ** MULTIPLIER **
    setBaitMultiplier(multiplier)
    setTrapMultiplier(multiplier)
    setZoneMultiplier(multiplier)
    -- setSizeAnimalMultiplier(multiplier)

    --                  ** Init bait/trap/zone **
    initBait()
    initTrap()
    initZone()
end

---**Get Squirrel**
---@return table Squirrel
function getSquirrel()
    init()
    return squirrel
end
