-----
----- Generated by EmmyLua(https://github.com/EmmyLua)
----- Created by lele.
----- DateTime: 09/08/23 10:17
-----
--

---@class TrappingSurvival

Animals = {}

local function init()
    table.insert(Animals, getBird())
    table.insert(Animals, getMouse())
    table.insert(Animals, getRabbit())
    table.insert(Animals, getRat())
    table.insert(Animals, getSquirrel())
end

init()
