---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 03/08/23 11:31
---

-- https://pzwiki.net/wiki/Trapping
-- SteamLibrary/steamapps/common/ProjectZomboid/projectzomboid/media/lua/server/Traps/TrapDefinition.lua

---@class Zone

local Zone = {}

local deepForest
local farmLand
local forest
local townZone
local trailerPark
local vegetation

----- **Enum Zone**
Zone.zone = {
    DEEP_FOREST = "DeepForest",
    FOREST = "Forest",
    TOWN_ZONE = "TownZone",
    TRAILER_PARK = "TrailerPark",
    VEGETATION = "Vegitation",
    FARM_LAND = "FarmLand",
}

--- **Set Deep Forest**
---@param deepForest_ int
function Zone.setDeepForest(deepForest_)
    if deepForest_ < 0 then
        print("ERROR : DEEPFOREST " .. tostring(deepForest_))
        return
    end

    deepForest = deepForest_
end

--- **Get Deep Forest**
---@return int deepForest
function Zone.getDeepForest()
    return deepForest
end

--- **Set FarmLand**
---@param farmland_ int
function Zone.setFarmLand(farmland_)
    if farmland_ < 0 then
        print("ERROR : FARMLAND " .. tostring(farmland_))
        return
    end

    farmLand = farmland_
end

--- **Get FarmLand**
---@return int FarmLand
function Zone.getFarmLand()
    return farmLand
end


--- **Set Forest**
---@param forest_ int
function Zone.setForest(forest_)
    if forest_ < 0 then
        print("ERROR : FOREST " .. tostring(forest_))
        return
    end

    forest = forest_
end

--- **Get Forest**
---@return int forest
function Zone.getForest()
    return forest
end

--- **Set Town Zone**
---@param townZone_ int
function Zone.setTownZone(townZone_)
    if townZone_ < 0 then
        print("ERROR : TOWNZONE " .. tostring(townZone_))
        return
    end

    townZone = townZone_
end

--- **Get Town Zone**
---@return int townZone
function Zone.getTownZone()
    return townZone
end

--- **Set Trailer Park**
---@param trailerPark_ int
function Zone.setTrailerPark(trailerPark_)
    if trailerPark_ < 0 then
        print("ERROR : TRAILERPARK " .. tostring(trailerPark_))
        return
    end

    trailerPark = trailerPark_
end

--- **Get Trailer Park**
---@return int trailerPark
function Zone.getTrailerPark()
    return trailerPark
end

--- **Set Vegetation**
---@param vegetation_ int
function Zone.setVegetation(vegetation_)
    if vegetation_ < 0 then
        print("ERROR : VEGETATION " .. tostring(vegetation_))
        return
    end

    vegetation = vegetation_
end

--- **Get Vegetation**
---@return int vegetation
function Zone.getVegetation()
    return vegetation
end

return Zone
