---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 13/08/23 12:07
---

-- https://pzwiki.net/wiki/Trapping
-- SteamLibrary/steamapps/common/ProjectZomboid/projectzomboid/media/lua/server/Traps/TrapDefinition.lua

---@class CreatureFactory

local CreatureFactory = {}

function CreatureFactory.creature(animal, strength, item, minSize, maxSize, minHour, maxHour, minTemp, maxTemp)
    local creature = {}
    creature.baits = {}
    creature.traps = {}
    creature.zone = {}
    creature.type = animal
    creature.strength = strength
    creature.item = item
    creature.minSize = minSize
    creature.maxSize = maxSize
    creature.minHour = minHour
    creature.maxHour = maxHour
    creature.minTemp = minTemp
    creature.maxTemp = maxTemp
    return creature
end

--- ---------------------- Start table bait/trap/zone -------------

--- **Create Bait**
---@param creature_ table -- baits
---@param baitEnum Enum
---@param bait string
function CreatureFactory.createBait(creature_, baitEnum, bait)
    creature_.baits[baitEnum] = bait
end

--- **Create Trap**
---@param creature_ table -- traps
---@param trapEnum Enum
---@param trap string
function CreatureFactory.createTrap(creature_, trapEnum, trap)
    creature_.traps[trapEnum] = trap
end

--- **Create Zone**
---@param creature_ table -- zone
---@param zoneEnum Enum
---@param zone string
function CreatureFactory.createZone(creature_, zoneEnum, zone)
    creature_.zone[zoneEnum] = zone
end

return CreatureFactory
