---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 13/08/23 23:14
---

-- https://pzwiki.net/wiki/Trapping
-- SteamLibrary/steamapps/common/ProjectZomboid/projectzomboid/media/lua/server/Traps/TrapDefinition.lua

---@class Mouse

local creatureFactory = require("CreatureFactory")
local mouse = {}

local trap = require("Trap")
local bait = require("Bait")
local zone = require("Zone")

--- ---------------------- Start Mouse Default values -------------------------------

--                  ** BAIT **
local cheese = 60
local chocolate = 30
local peanutButter = 40
local processedCheese = 55
local tomato = 35

--                  ** ZONE **
local deepForest = 10
local farmLand = 60
local forest = 10
local townZone = 50
local trailerPark = 60
local vegetation = 20

--                  ** TRAP **
local trapMouse = 30

--                  ** ANIMALS **
-- Type of animal
local type = "mouse"

-- after how many hour the animal will start to destroy the cage/escape
local strength = 24

-- item given to the player
local item = "Base.DeadMouse"

-- hour this animal will be out and when you can catch it
local minHour = 0
local maxHour = 0

-- min and max "size" (understand hunger reduction) of the animal
local minSize = 1
local maxSize = 10

-- min and max temperature of the animal
local minTemp = -5
local maxTemp = 30

--- ---------------------- Start Set Multiplier -------------------

--- **Set Bait Multiplier**
---@param multiplier int
local function setBaitMultiplier(multiplier)
    bait.setCheese(cheese * multiplier)
    bait.setChocolate(chocolate * multiplier)
    bait.setPeanutButter(peanutButter * multiplier)
    bait.setProcessedCheese(processedCheese * multiplier)
    bait.setTomato(tomato * multiplier)
end

--- **Set Trap Multiplier**
---@param multiplier int
local function setTrapMultiplier(multiplier)
    trap.setTrapMouse(trapMouse * multiplier)
end

--- **Set Zone Multiplier**
---@param multiplier int
local function setZoneMultiplier(multiplier)
    zone.setDeepForest(deepForest * multiplier)
    zone.setFarmLand(farmLand * multiplier)
    zone.setForest(forest * multiplier)
    zone.setTownZone(townZone * multiplier)
    zone.setTrailerPark(trailerPark * multiplier)
    zone.setVegetation(vegetation * multiplier)
end

--- **Set "size" Multiplier**
--- Min and max "size" (understand hunger reduction) of the animal
---@param multiplier int
local function setSizeAnimalMultiplier(multiplier)
    mouse.minSize = minSize * multiplier;
    mouse.maxSize = maxSize * multiplier;
end

--- ---------------------- Start init Bait -------------------

--- **Init Bait**
local function initBait()
    creatureFactory.createBait(mouse, bait.bait.CHEESE, bait.getCheese())
    creatureFactory.createBait(mouse, bait.bait.CHOCOLATE, bait.getChocolate())
    creatureFactory.createBait(mouse, bait.bait.PEANUT_BUTTER, bait.getPeanutButter())
    creatureFactory.createBait(mouse, bait.bait.PROCESSED_CHEESE, bait.getProcessedCheese())
    creatureFactory.createBait(mouse, bait.bait.TOMATO, bait.getTomato())
end

--- **Init Trap**
local function initTrap()
    creatureFactory.createTrap(mouse, trap.trap.MOUSE, trap.getTrapMouse())
end

--- **Init Zone**
local function initZone()
    creatureFactory.createZone(mouse, zone.zone.DEEP_FOREST, zone.getDeepForest())
    creatureFactory.createZone(mouse, zone.zone.FOREST, zone.getForest())
    creatureFactory.createZone(mouse, zone.zone.TOWN_ZONE, zone.getTownZone())
    creatureFactory.createZone(mouse, zone.zone.TRAILER_PARK, zone.getTrailerPark())
    creatureFactory.createZone(mouse, zone.zone.VEGETATION, zone.getVegetation())
end

--- **Init**
local function init()
    local multiplier = SandboxVars.TrappingSurvival.Mouse
    mouse = creatureFactory.creature(type, strength, item, maxSize, minSize, minHour, maxHour, minTemp, maxTemp)

    --                  ** MULTIPLIER **
    setBaitMultiplier(multiplier)
    setTrapMultiplier(multiplier)
    setZoneMultiplier(multiplier)
    -- setSizeAnimalMultiplier(multiplier)

    --                  ** Init bait/trap/zone **
    initBait()
    initTrap()
    initZone()

end

---**Get Mouse**
---@return table Mouse
function getMouse()
    init()
    return mouse
end
